#ifndef _BS_IMAGE_DECODER_H_
#define _BS_IMAGE_DECODER_H_

#include <common.h>
#include <stdint.h>
#include <stddef.h>

// Decodes a texture blob (PNG, GameMaker custom QOI, or BZip2+QOI) into RGBA8 pixel data.
// "gm2022_5" should be set when it is a QOI image generated by GameMaker 2022.5+, because it includes the uncompressed length in the header.
// Returns a buffer of size (*outW) * (*outH) * 4 bytes, or nullptr on failure.
// Free with ImageDecoder_freeRgba (not raw free) — Wii large decodes may use a MEM2 arena.
uint8_t* ImageDecoder_decodeToRgba(const uint8_t* blob, size_t blobSize, bool gm2022_5, int* outW, int* outH);

// Wii: bracket large decodes so scratch comes from MEM2 arena (LIFO). Nested calls OK.
// After endArenaTemp, any pixels decoded inside the bracket are invalid.
void ImageDecoder_beginArenaTemp(void);
void ImageDecoder_endArenaTemp(void);
int ImageDecoder_arenaTempActive(void);
void ImageDecoder_freeRgba(uint8_t* pixels);

#endif /* _BS_IMAGE_DECODER_H_ */
